import React, { useMemo, useState } from 'react';
import { ArrowRight, Check, Info, Layers, ShoppingBag } from 'lucide-react';
import { Language } from '../types';
import { playSyntheticChime, pickLang, SELECTABLE_LANGUAGES } from '../data';
import { speakText } from './VoiceHelper';

type UserType = 'producer' | 'buyer';
type ProducerType = 'individual_artisan' | 'cooperative_society' | 'shg_ngo';
type BuyerType = 'individual_consumer' | 'boutique_retailer' | 'institutional_corporate' | 'wholesale_exporter';
type AccountType = ProducerType | BuyerType;
type FieldType = 'text' | 'textarea' | 'email' | 'tel' | 'number' | 'select';

interface FormField { key: string; label: string; type?: FieldType; required?: boolean; options?: string[]; condition?: (values: Record<string, string>) => boolean; }
interface OnboardingFlowProps { language: Language; setLanguage: (lang: Language) => void; onComplete: (profile: any) => void; }

const optionSets = {
  en: { crafts: ['Handloom & Textiles', 'Pottery & Ceramics', 'Woodcraft', 'Metalcraft', 'Jewellery', 'Leathercraft', 'Bamboo & Cane', 'Embroidery', 'Folk Painting', 'Traditional Toys', 'Other Handicrafts'], buyerCrafts: ['Sarees & Textiles', 'Pottery', 'Jewellery', 'Woodcraft', 'Metalcraft', 'Bamboo & Cane', 'Embroidery', 'Folk Art', 'Home Decor', 'Other Handicrafts'], payout: ['Bank Account', 'UPI'], counts: ['Under 50', '50-200', '200-500', '500+'], organization: ['Self-Help Group', 'NGO', 'Community Organization', 'Artisan Cluster'], assistance: ['Digital Cataloguing', 'Voice-Based Product Listing', 'Digital Payments', 'Market Access', 'Training & Support', 'Multiple Services'], shopping: ['Personal Use', 'Gifts', 'Home Decor', 'Cultural / Traditional Products'], volume: ['Small Bulk Orders', 'Medium Bulk Orders', 'Large Bulk Orders'], frequency: ['Monthly', 'Quarterly', 'Seasonal', 'As Required'], institution: ['Corporate', 'Hotel / Hospitality', 'Educational Institution', 'Government Organization', 'NGO', 'Other Institution'], purpose: ['Corporate Gifting', 'Events', 'Interior / Hospitality Decor', 'Uniforms', 'Institutional Requirements', 'Other'], payment: ['Advance Payment', 'Purchase Order', 'Bank Transfer', 'Other Approved Method'], markets: ['North America', 'Europe', 'Middle East', 'Asia-Pacific', 'Africa', 'Other Markets'], certifications: ['Handloom Mark', 'Silk Mark', 'GI Certification', 'Fair Trade', 'Other', 'None'], yesNo: ['Yes', 'No'] },
  kn: { crafts: ['ಕೈಮಗ್ಗ ಮತ್ತು ಜವಳಿ', 'ಮಣ್ಣಿನ ಪಾತ್ರೆ ಮತ್ತು ಸೆರಾಮಿಕ್', 'ಮರದ ಕಲೆ', 'ಲೋಹದ ಕಲೆ', 'ಆಭರಣ', 'ಚರ್ಮದ ಕಲೆ', 'ಬಿದಿರು ಮತ್ತು ಕೇನ್', 'ಕಸೂತಿ', 'ಜನಪದ ಚಿತ್ರಕಲೆ', 'ಸಾಂಪ್ರದಾಯಿಕ ಆಟಿಕೆಗಳು', 'ಇತರ ಕರಕುಶಲಗಳು'], buyerCrafts: ['ಸೀರೆ ಮತ್ತು ಜವಳಿ', 'ಮಣ್ಣಿನ ಕಲೆ', 'ಆಭರಣ', 'ಮರದ ಕಲೆ', 'ಲೋಹದ ಕಲೆ', 'ಬಿದಿರು ಮತ್ತು ಕೇನ್', 'ಕಸೂತಿ', 'ಜನಪದ ಕಲೆ', 'ಮನೆಯ ಅಲಂಕಾರ', 'ಇತರ ಕರಕುಶಲಗಳು'], payout: ['ಬ್ಯಾಂಕ್ ಖಾತೆ', 'ಯುಪಿಐ'], counts: ['೫೦ ಕ್ಕಿಂತ ಕಡಿಮೆ', '೫೦-೨೦೦', '೨೦೦-೫೦೦', '೫೦೦+'], organization: ['ಸ್ವಸಹಾಯ ಗುಂಪು', 'ಎನ್‌ಜಿಒ', 'ಸಮುದಾಯ ಸಂಸ್ಥೆ', 'ಕುಶಲಕರ್ಮಿ ಕ್ಲಸ್ಟರ್'], assistance: ['ಡಿಜಿಟಲ್ ಪಟ್ಟಿಮಾಡುವಿಕೆ', 'ಧ್ವನಿ ಆಧಾರಿತ ಉತ್ಪನ್ನ ಪಟ್ಟಿ', 'ಡಿಜಿಟಲ್ ಪಾವತಿಗಳು', 'ಮಾರುಕಟ್ಟೆ ಸಂಪರ್ಕ', 'ತರಬೇತಿ ಮತ್ತು ಬೆಂಬಲ', 'ಹಲವು ಸೇವೆಗಳು'], shopping: ['ವೈಯಕ್ತಿಕ ಬಳಕೆ', 'ಉಡುಗೊರೆಗಳು', 'ಮನೆಯ ಅಲಂಕಾರ', 'ಸಾಂಸ್ಕೃತಿಕ / ಸಾಂಪ್ರದಾಯಿಕ ಉತ್ಪನ್ನಗಳು'], volume: ['ಸಣ್ಣ ಪ್ರಮಾಣದ ಸಗಟು ಆರ್ಡರ್', 'ಮಧ್ಯಮ ಪ್ರಮಾಣದ ಸಗಟು ಆರ್ಡರ್', 'ದೊಡ್ಡ ಪ್ರಮಾಣದ ಸಗಟು ಆರ್ಡರ್'], frequency: ['ತಿಂಗಳಿಗೆ', 'ತ್ರೈಮಾಸಿಕವಾಗಿ', 'ಋತುವಿನಂತೆ', 'ಅಗತ್ಯವಿದ್ದಾಗ'], institution: ['ಕಂಪನಿ', 'ಹೋಟೆಲ್ / ಆತಿಥ್ಯ', 'ಶೈಕ್ಷಣಿಕ ಸಂಸ್ಥೆ', 'ಸರ್ಕಾರಿ ಸಂಸ್ಥೆ', 'ಎನ್‌ಜಿಒ', 'ಇತರ ಸಂಸ್ಥೆ'], purpose: ['ಕಂಪನಿ ಉಡುಗೊರೆಗಳು', 'ಕಾರ್ಯಕ್ರಮಗಳು', 'ಒಳಾಂಗಣ / ಆತಿಥ್ಯ ಅಲಂಕಾರ', 'ಸಮವಸ್ತ್ರಗಳು', 'ಸಂಸ್ಥೆಯ ಅಗತ್ಯಗಳು', 'ಇತರೆ'], payment: ['ಮುಂಗಡ ಪಾವತಿ', 'ಖರೀದಿ ಆದೇಶ', 'ಬ್ಯಾಂಕ್ ವರ್ಗಾವಣೆ', 'ಇತರ ಅನುಮೋದಿತ ವಿಧಾನ'], markets: ['ಉತ್ತರ ಅಮೆರಿಕಾ', 'ಯುರೋಪ್', 'ಮಧ್ಯಪ್ರಾಚ್ಯ', 'ಏಷ್ಯಾ-ಪೆಸಿಫಿಕ್', 'ಆಫ್ರಿಕಾ', 'ಇತರ ಮಾರುಕಟ್ಟೆಗಳು'], certifications: ['ಕೈಮಗ್ಗ ಗುರುತು', 'ರೇಷ್ಮೆ ಗುರುತು', 'ಜಿಐ ಪ್ರಮಾಣೀಕರಣ', 'ನ್ಯಾಯಯುತ ವ್ಯಾಪಾರ', 'ಇತರೆ', 'ಯಾವುದೂ ಇಲ್ಲ'], yesNo: ['ಹೌದು', 'ಇಲ್ಲ'] },
  hi: { crafts: ['हथकरघा और वस्त्र', 'मिट्टी के बर्तन और सिरेमिक', 'लकड़ी का शिल्प', 'धातु शिल्प', 'आभूषण', 'चमड़े का शिल्प', 'बांस और बेंत', 'कढ़ाई', 'लोक चित्रकला', 'पारंपरिक खिलौने', 'अन्य हस्तशिल्प'], buyerCrafts: ['साड़ी और वस्त्र', 'मिट्टी का शिल्प', 'आभूषण', 'लकड़ी का शिल्प', 'धातु शिल्प', 'बांस और बेंत', 'कढ़ाई', 'लोक कला', 'घर की सजावट', 'अन्य हस्तशिल्प'], payout: ['बैंक खाता', 'यूपीआई'], counts: ['50 से कम', '50-200', '200-500', '500+'], organization: ['स्वयं सहायता समूह', 'एनजीओ', 'सामुदायिक संगठन', 'कारीगर क्लस्टर'], assistance: ['डिजिटल सूची बनाना', 'वॉयस आधारित उत्पाद सूची', 'डिजिटल भुगतान', 'बाजार संपर्क', 'प्रशिक्षण और सहायता', 'कई सेवाएं'], shopping: ['व्यक्तिगत उपयोग', 'उपहार', 'घर की सजावट', 'सांस्कृतिक / पारंपरिक उत्पाद'], volume: ['छोटे थोक ऑर्डर', 'मध्यम थोक ऑर्डर', 'बड़े थोक ऑर्डर'], frequency: ['मासिक', 'त्रैमासिक', 'मौसमी', 'आवश्यकतानुसार'], institution: ['कंपनी', 'होटल / आतिथ्य', 'शैक्षणिक संस्था', 'सरकारी संस्था', 'एनजीओ', 'अन्य संस्था'], purpose: ['कॉर्पोरेट उपहार', 'कार्यक्रम', 'इंटीरियर / आतिथ्य सजावट', 'वर्दी', 'संस्थागत आवश्यकताएं', 'अन्य'], payment: ['अग्रिम भुगतान', 'खरीद आदेश', 'बैंक ट्रांसफर', 'अन्य स्वीकृत तरीका'], markets: ['उत्तरी अमेरिका', 'यूरोप', 'मध्य पूर्व', 'एशिया-प्रशांत', 'अफ्रीका', 'अन्य बाजार'], certifications: ['हथकरघा मार्क', 'सिल्क मार्क', 'जीआई प्रमाणन', 'अन्य', 'कोई नहीं'], yesNo: ['हाँ', 'नहीं'] },
  ta: { crafts: ['கைத்தறி மற்றும் ஜவுளி', 'மட்பாண்டம் மற்றும் செராமிக்', 'மரவேலை', 'உலோகக் கலை', 'நகைகள்', 'தோல் கைவினை', 'மூங்கில் மற்றும் பிரம்பு', 'எம்பிராய்டரி', 'நாட்டுப்புற ஓவியம்', 'பாரம்பரிய பொம்மைகள்', 'மற்ற கைவினைப்பொருட்கள்'], buyerCrafts: ['புடவைகள் மற்றும் ஜவுளி', 'மட்பாண்டம்', 'நகைகள்', 'மரவேலை', 'உலோகக் கலை', 'மூங்கில் மற்றும் பிரம்பு', 'எம்பிராய்டரி', 'நாட்டுப்புற கலை', 'வீட்டு அலங்காரம்', 'மற்ற கைவினைப்பொருட்கள்'], payout: ['வங்கிக் கணக்கு', 'UPI'], counts: ['50க்கும் குறைவு', '50-200', '200-500', '500+'], organization: ['சுய உதவிக் குழு', 'என்ஜிஓ', 'சமூக அமைப்பு', 'கைவினைஞர் கிளஸ்டர்'], assistance: ['டிஜிட்டல் பட்டியலிடல்', 'குரல் அடிப்படையிலான தயாரிப்பு பட்டியல்', 'டிஜிட்டல் பணம் செலுத்துதல்', 'சந்தை அணுகல்', 'பயிற்சி & ஆதரவு', 'பல சேவைகள்'], shopping: ['தனிப்பட்ட பயன்பாடு', 'பரிசுகள்', 'வீட்டு அலங்காரம்', 'கலாச்சார / பாரம்பரிய பொருட்கள்'], volume: ['சிறிய மொத்த ஆர்டர்கள்', 'நடுத்தர மொத்த ஆர்டர்கள்', 'பெரிய மொத்த ஆர்டர்கள்'], frequency: ['மாதாந்திரம்', 'காலாண்டு', 'பருவகாலம்', 'தேவைக்கேற்ப'], institution: ['நிறுவனம்', 'ஹோட்டல் / விருந்தோம்பல்', 'கல்வி நிறுவனம்', 'அரசு நிறுவனம்', 'என்ஜிஓ', 'மற்ற நிறுவனம்'], purpose: ['நிறுவன பரிசுகள்', 'நிகழ்வுகள்', 'உள்துறை / விருந்தோம்பல் அலங்காரம்', 'சீருடைகள்', 'நிறுவன தேவைகள்', 'மற்றவை'], payment: ['முன்பணம்', 'கொள்முதல் ஆணை', 'வங்கி பரிமாற்றம்', 'மற்ற அங்கீகரிக்கப்பட்ட முறை'], markets: ['வட அமெரிக்கா', 'ஐரோப்பா', 'மத்திய கிழக்கு', 'ஆசியா-பசிபிக்', 'ஆப்பிரிக்கா', 'மற்ற சந்தைகள்'], certifications: ['கைத்தறி முத்திரை', 'பட்டு முத்திரை', 'GI சான்றிதழ்', 'நியாய வர்த்தகம்', 'மற்றவை', 'ஏதுமில்லை'], yesNo: ['ஆம்', 'இல்லை'] }
};

const copy = {
  en: { welcome: 'Welcome to KalaSetu', tagline: 'A direct marketplace for authentic Indian artisans, creators, and buyers.', language: 'Choose your comfortable language', account: 'Choose your account type', producer: 'I am a Producer / Creator', producerDesc: 'List authentic crafts, manage orders, and receive direct payments.', buyer: 'I am a Buyer / Market Partner', buyerDesc: 'Discover verified Indian crafts for personal, retail, institutional, or export buying.', producerChoice: 'Choose your producer type', buyerChoice: 'Choose your buyer type', details: 'Complete your profile', detailsDesc: 'Only the fields needed for your selected account type are shown.', continue: 'Continue', back: 'Go Back', create: 'Create Account', step: 'Step', select: 'Select', required: 'Please complete the required fields.', mobile: 'Enter a valid Indian mobile number.', email: 'Enter a valid email address.', pincode: 'Enter a valid 6-digit pincode.', gstin: 'Enter a valid GSTIN.', iec: 'Enter a valid IEC.', options: { individual_artisan: 'Individual Artisan / Independent Creator', cooperative_society: 'Co-operative Society / Aggregator', shg_ngo: 'Artisan Self-Help Group (SHG) / NGO', individual_consumer: 'Individual Consumer / Retail Buyer', boutique_retailer: 'Boutique Retailer / B2B Bulk Buyer', institutional_corporate: 'Institutional & Corporate Buyer', wholesale_exporter: 'Wholesale Exporter / Global Distributor' }, titles: { individual_artisan: 'Create Your Artisan Profile', cooperative_society: 'Register Your Co-operative Society', shg_ngo: 'Set Up Your Artisan Group', individual_consumer: 'Create Your Buyer Profile', boutique_retailer: 'Set Up Your Business Buying Profile', institutional_corporate: 'Create Your Institutional Procurement Profile', wholesale_exporter: 'Set Up Your Global Distribution Profile' } },
  kn: { welcome: 'ಕಲಾಸೇತುಗೆ ಸ್ವಾಗತ', tagline: 'ಭಾರತೀಯ ಕುಶಲಕರ್ಮಿಗಳು, ಸೃಜನಶೀಲರು ಮತ್ತು ಖರೀದಿದಾರರಿಗೆ ನೇರ ಮಾರುಕಟ್ಟೆ.', language: 'ನಿಮಗೆ ಅನುಕೂಲವಾದ ಭಾಷೆಯನ್ನು ಆರಿಸಿ', account: 'ನಿಮ್ಮ ಖಾತೆಯ ಪ್ರಕಾರವನ್ನು ಆರಿಸಿ', producer: 'ನಾನು ಉತ್ಪಾದಕ / ಸೃಜನಶೀಲ', producerDesc: 'ನಿಮ್ಮ ಕರಕುಶಲ ಉತ್ಪನ್ನಗಳನ್ನು ಪಟ್ಟಿ ಮಾಡಿ, ಆರ್ಡರ್ ನಿರ್ವಹಿಸಿ ಮತ್ತು ನೇರ ಪಾವತಿ ಪಡೆಯಿರಿ.', buyer: 'ನಾನು ಖರೀದಿದಾರ / ಮಾರುಕಟ್ಟೆ ಪಾಲುದಾರ', buyerDesc: 'ವೈಯಕ್ತಿಕ, ಚಿಲ್ಲರೆ, ಸಂಸ್ಥೆ ಅಥವಾ ರಫ್ತು ಖರೀದಿಗಾಗಿ ಪರಿಶೀಲಿತ ಭಾರತೀಯ ಕರಕುಶಲಗಳನ್ನು ಕಂಡುಕೊಳ್ಳಿ.', producerChoice: 'ಉತ್ಪಾದಕರ ಪ್ರಕಾರವನ್ನು ಆರಿಸಿ', buyerChoice: 'ಖರೀದಿದಾರರ ಪ್ರಕಾರವನ್ನು ಆರಿಸಿ', details: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ', detailsDesc: 'ನಿಮ್ಮ ಆಯ್ಕೆಯ ಖಾತೆಗೆ ಅಗತ್ಯವಿರುವ ಕ್ಷೇತ್ರಗಳನ್ನು ಮಾತ್ರ ತೋರಿಸಲಾಗುತ್ತದೆ.', continue: 'ಮುಂದೆ', back: 'ಹಿಂದೆ', create: 'ಖಾತೆ ರಚಿಸಿ', step: 'ಹಂತ', select: 'ಆಯ್ಕೆಮಾಡಿ', required: 'ಅಗತ್ಯವಿರುವ ಕ್ಷೇತ್ರಗಳನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ.', mobile: 'ಮಾನ್ಯವಾದ ಭಾರತೀಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ.', email: 'ಮಾನ್ಯವಾದ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ.', pincode: 'ಮಾನ್ಯವಾದ ೬ ಅಂಕಿಯ ಪಿನ್‌ಕೋಡ್ ನಮೂದಿಸಿ.', gstin: 'ಮಾನ್ಯವಾದ ಜಿಎಸ್‌ಟಿಐಎನ್ ನಮೂದಿಸಿ.', iec: 'ಮಾನ್ಯವಾದ ಐಇಸಿ ನಮೂದಿಸಿ.', options: { individual_artisan: 'ವೈಯಕ್ತಿಕ ಕುಶಲಕರ್ಮಿ / ಸ್ವತಂತ್ರ ಸೃಜನಶೀಲ', cooperative_society: 'ಸಹಕಾರ ಸಂಘ / ಸಂಗ್ರಾಹಕ', shg_ngo: 'ಕುಶಲಕರ್ಮಿ ಸ್ವಸಹಾಯ ಗುಂಪು (SHG) / NGO', individual_consumer: 'ವೈಯಕ್ತಿಕ ಗ್ರಾಹಕ / ಚಿಲ್ಲರೆ ಖರೀದಿದಾರ', boutique_retailer: 'ಬುಟಿಕ್ ಚಿಲ್ಲರೆ ವ್ಯಾಪಾರಿ / B2B ಸಗಟು ಖರೀದಿದಾರ', institutional_corporate: 'ಸಂಸ್ಥೆ ಮತ್ತು ಕಂಪನಿ ಖರೀದಿದಾರ', wholesale_exporter: 'ಸಗಟು ರಫ್ತುದಾರ / ಜಾಗತಿಕ ವಿತರಕ' }, titles: { individual_artisan: 'ನಿಮ್ಮ ಕುಶಲಕರ್ಮಿ ಪ್ರೊಫೈಲ್ ರಚಿಸಿ', cooperative_society: 'ನಿಮ್ಮ ಸಹಕಾರ ಸಂಘವನ್ನು ನೋಂದಾಯಿಸಿ', shg_ngo: 'ನಿಮ್ಮ ಕುಶಲಕರ್ಮಿ ಗುಂಪನ್ನು ಸಿದ್ಧಪಡಿಸಿ', individual_consumer: 'ನಿಮ್ಮ ಖರೀದಿದಾರರ ಪ್ರೊಫೈಲ್ ರಚಿಸಿ', boutique_retailer: 'ನಿಮ್ಮ ವ್ಯಾಪಾರ ಖರೀದಿ ಪ್ರೊಫೈಲ್ ಸಿದ್ಧಪಡಿಸಿ', institutional_corporate: 'ನಿಮ್ಮ ಸಂಸ್ಥೆಯ ಖರೀದಿ ಪ್ರೊಫೈಲ್ ರಚಿಸಿ', wholesale_exporter: 'ನಿಮ್ಮ ಜಾಗತಿಕ ವಿತರಣಾ ಪ್ರೊಫೈಲ್ ಸಿದ್ಧಪಡಿಸಿ' } },
  hi: { welcome: 'कलासेतु में आपका स्वागत है', tagline: 'भारतीय कारीगरों, रचनाकारों और खरीदारों के लिए सीधा बाजार।', language: 'अपनी सुविधाजनक भाषा चुनें', account: 'अपना खाता प्रकार चुनें', producer: 'मैं एक उत्पादक / रचनाकार हूँ', producerDesc: 'अपने हस्तशिल्प सूचीबद्ध करें, ऑर्डर संभालें और सीधे भुगतान पाएं।', buyer: 'मैं एक खरीदार / बाजार भागीदार हूँ', buyerDesc: 'व्यक्तिगत, खुदरा, संस्थागत या निर्यात खरीद के लिए प्रमाणित भारतीय शिल्प खोजें।', producerChoice: 'उत्पादक का प्रकार चुनें', buyerChoice: 'खरीदार का प्रकार चुनें', details: 'अपना प्रोफाइल पूरा करें', detailsDesc: 'आपके चुने हुए खाते के लिए जरूरी फ़ील्ड ही दिखाए गए हैं।', continue: 'आगे', back: 'पीछे', create: 'खाता बनाएं', step: 'चरण', select: 'चुनें', required: 'कृपया जरूरी फ़ील्ड भरें।', mobile: 'मान्य भारतीय मोबाइल नंबर दर्ज करें।', email: 'मान्य ईमेल पता दर्ज करें।', pincode: 'मान्य 6 अंकों का पिनकोड दर्ज करें।', gstin: 'मान्य जीएसटीआईएन दर्ज करें।', iec: 'मान्य आईईसी दर्ज करें।', options: { individual_artisan: 'व्यक्तिगत कारीगर / स्वतंत्र रचनाकार', cooperative_society: 'सहकारी समिति / संग्रहकर्ता', shg_ngo: 'कारीगर स्वयं सहायता समूह (SHG) / NGO', individual_consumer: 'व्यक्तिगत उपभोक्ता / खुदरा खरीदार', boutique_retailer: 'बुटीक खुदरा विक्रेता / B2B थोक खरीदार', institutional_corporate: 'संस्थागत और कॉर्पोरेट खरीदार', wholesale_exporter: 'थोक निर्यातक / वैश्विक वितरक' }, titles: { individual_artisan: 'अपना कारीगर प्रोफाइल बनाएं', cooperative_society: 'अपनी सहकारी समिति पंजीकृत करें', shg_ngo: 'अपना कारीगर समूह बनाएं', individual_consumer: 'अपना खरीदार प्रोफाइल बनाएं', boutique_retailer: 'अपना व्यापारिक खरीद प्रोफाइल बनाएं', institutional_corporate: 'अपना संस्थागत खरीद प्रोफाइल बनाएं', wholesale_exporter: 'अपना वैश्विक वितरण प्रोफाइल बनाएं' } },
  ta: { welcome: 'கலாசேதுவிற்கு வரவேற்கிறோம்', tagline: 'உண்மையான இந்திய கைவினைஞர்கள், படைப்பாளிகள் மற்றும் வாங்குபவர்களுக்கான நேரடி சந்தை.', language: 'உங்களுக்கு வசதியான மொழியைத் தேர்ந்தெடுக்கவும்', account: 'உங்கள் கணக்கு வகையைத் தேர்ந்தெடுக்கவும்', producer: 'நான் ஒரு உற்பத்தியாளர் / படைப்பாளி', producerDesc: 'உண்மையான கைவினைப்பொருட்களைப் பட்டியலிடுங்கள், ஆர்டர்களை நிர்வகிக்கவும், நேரடி பணம் பெறவும்.', buyer: 'நான் ஒரு வாங்குபவர் / சந்தை பங்குதாரர்', buyerDesc: 'தனிப்பட்ட, சில்லறை, நிறுவன அல்லது ஏற்றுமதி வாங்குதலுக்காக சரிபார்க்கப்பட்ட இந்திய கைவினைப்பொருட்களைக் கண்டறியுங்கள்.', producerChoice: 'உங்கள் உற்பத்தியாளர் வகையைத் தேர்ந்தெடுக்கவும்', buyerChoice: 'உங்கள் வாங்குபவர் வகையைத் தேர்ந்தெடுக்கவும்', details: 'உங்கள் சுயவிவரத்தை முடிக்கவும்', detailsDesc: 'நீங்கள் தேர்ந்தெடுத்த கணக்கு வகைக்குத் தேவையான புலங்கள் மட்டுமே காட்டப்படும்.', continue: 'தொடரவும்', back: 'திரும்பிச் செல்', create: 'கணக்கை உருவாக்கு', step: 'படி', select: 'தேர்ந்தெடு', required: 'தேவையான புலங்களை நிரப்பவும்.', mobile: 'சரியான இந்திய மொபைல் எண்ணை உள்ளிடவும்.', email: 'சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்.', pincode: 'சரியான 6-இலக்க பின்கோடை உள்ளிடவும்.', gstin: 'சரியான GSTIN-ஐ உள்ளிடவும்.', iec: 'சரியான IEC-ஐ உள்ளிடவும்.', options: { individual_artisan: 'தனிப்பட்ட கைவினைஞர் / சுயாதீன படைப்பாளி', cooperative_society: 'கூட்டுறவு சங்கம் / திரட்டி', shg_ngo: 'கைவினைஞர் சுய உதவிக் குழு (SHG) / NGO', individual_consumer: 'தனிப்பட்ட நுகர்வோர் / சில்லறை வாங்குபவர்', boutique_retailer: 'பூட்டிக் சில்லறை விற்பனையாளர் / B2B மொத்த வாங்குபவர்', institutional_corporate: 'நிறுவன & கார்ப்பரேட் வாங்குபவர்', wholesale_exporter: 'மொத்த ஏற்றுமதியாளர் / உலகளாவிய விநியோகஸ்தர்' }, titles: { individual_artisan: 'உங்கள் கைவினைஞர் சுயவிவரத்தை உருவாக்கவும்', cooperative_society: 'உங்கள் கூட்டுறவு சங்கத்தைப் பதிவு செய்யவும்', shg_ngo: 'உங்கள் கைவினைஞர் குழுவை அமைக்கவும்', individual_consumer: 'உங்கள் வாங்குபவர் சுயவிவரத்தை உருவாக்கவும்', boutique_retailer: 'உங்கள் வணிக வாங்குதல் சுயவிவரத்தை அமைக்கவும்', institutional_corporate: 'உங்கள் நிறுவன கொள்முதல் சுயவிவரத்தை உருவாக்கவும்', wholesale_exporter: 'உங்கள் உலகளாவிய விநியோக சுயவிவரத்தை அமைக்கவும்' } }
};

const languageSelectionCopy = {
  en: {
    welcome: 'Welcome to KalaSetu',
    tagline: 'A direct marketplace for authentic Indian artisans, creators, and buyers.',
    language: 'CHOOSE YOUR COMFORTABLE LANGUAGE',
    continue: 'Continue'
  },
  kn: {
    welcome: 'KalaSetu ಗೆ ಸುಸ್ವಾಗತ',
    tagline: 'ಅಧಿಕೃತ ಭಾರತೀಯ ಕುಶಲಕರ್ಮಿಗಳು, ಸೃಷ್ಟಿಕರ್ತರು ಮತ್ತು ಖರೀದಿದಾರರಿಗಾಗಿ ನೇರ ಮಾರುಕಟ್ಟೆ.',
    language: 'ನಿಮಗೆ ಅನುಕೂಲವಾದ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    continue: 'ಮುಂದುವರಿಸಿ'
  },
  hi: {
    welcome: 'KalaSetu में आपका स्वागत है',
    tagline: 'प्रामाणिक भारतीय कारीगरों, रचनाकारों और खरीदारों के लिए एक सीधा बाज़ार।',
    language: 'अपनी सुविधाजनक भाषा चुनें',
    continue: 'जारी रखें'
  },
  ta: {
    welcome: 'KalaSetu-க்கு அன்பான வரவேற்பு',
    tagline: 'உண்மையான இந்திய கைவினைஞர்கள், படைப்பாளிகள் மற்றும் வாங்குபவர்களுக்கான நேரடி சந்தை.',
    language: 'உங்களுக்கு வசதியான மொழியைத் தேர்ந்தெடுக்கவும்',
    continue: 'தொடரவும்'
  }
};

type FieldKey = 'fullName' | 'craftName' | 'primaryCraft' | 'specialty' | 'experience' | 'village' | 'district' | 'state' | 'mobile' | 'payoutMethod' | 'holderName' | 'accountNumber' | 'ifsc' | 'upi' | 'societyName' | 'registrationNumber' | 'licenseDetails' | 'headOffice' | 'artisanCount' | 'primaryCategories' | 'representative' | 'representativeMobile' | 'officialEmail' | 'bankAccount' | 'signatory' | 'groupName' | 'organizationType' | 'manager' | 'email' | 'baseLocation' | 'supportedArtisans' | 'clusters' | 'mainCategories' | 'organizationId' | 'assistance' | 'deliveryAddress' | 'city' | 'pincode' | 'preferredCategories' | 'shopping' | 'businessName' | 'owner' | 'gstin' | 'businessAddress' | 'businessEmail' | 'contact' | 'orderVolume' | 'preferredCrafts' | 'frequency' | 'resale' | 'companyName' | 'registeredAddress' | 'procurementOfficer' | 'procurementEmail' | 'officialContact' | 'purpose' | 'purchaseVolume' | 'payment' | 'tradingName' | 'authorizedRepresentative' | 'iec' | 'internationalContact' | 'markets' | 'port' | 'compliance' | 'logisticsSupport' | 'capacityPerWeek' | 'capacityPerMonth';

const fieldLabels: { en: Record<FieldKey, string> } & Partial<Record<Language, Record<FieldKey, string>>> = {
  en: { fullName: 'Full Name', craftName: 'Artisan / Craft Name', primaryCraft: 'Primary Craft Category', specialty: 'Craft / Product Specialty', experience: 'Years of Craft Experience', village: 'Village / Town', district: 'District', state: 'State', mobile: 'Mobile Number (Optional)', payoutMethod: 'Preferred Payout Method', holderName: 'Account Holder Name', accountNumber: 'Account Number', ifsc: 'IFSC', upi: 'UPI ID', societyName: 'Registered Society Name', registrationNumber: 'Registration Number', licenseDetails: 'Government Registration / License Details', headOffice: 'Head Office Address', artisanCount: 'Number of Artisans Represented', primaryCategories: 'Primary Craft Categories', representative: 'Society Representative Name', representativeMobile: 'Representative Mobile Number (Optional)', officialEmail: 'Official Email', bankAccount: 'Centralized Bank Account', signatory: 'Authorized Signatory Name', groupName: 'SHG / NGO Name', organizationType: 'Organization Type', manager: 'Group Representative / Field Manager Name', email: 'Email', baseLocation: 'Base Village / Location', supportedArtisans: 'Number of Artisans Supported', clusters: 'Number of Clusters Managed', mainCategories: 'Main Craft Categories', organizationId: 'Registration / Organization ID', assistance: 'Assistance Required', deliveryAddress: 'Delivery Address', city: 'City / Town', pincode: 'Pincode', preferredCategories: 'Preferred Product Categories', shopping: 'Shopping Preference', businessName: 'Boutique / Business Name', owner: 'Owner / Buyer Name', gstin: 'GSTIN', businessAddress: 'Business Address', businessEmail: 'Business Email', contact: 'Contact Number (Optional)', orderVolume: 'Expected Order Volume', preferredCrafts: 'Preferred Craft Categories', frequency: 'Typical Order Frequency', resale: 'Do you purchase for resale?', companyName: 'Organization / Company Name', registeredAddress: 'Registered Office Address', procurementOfficer: 'Procurement Officer Name', procurementEmail: 'Official Procurement Email', officialContact: 'Official Contact Number (Optional)', purpose: 'Procurement Purpose', purchaseVolume: 'Expected Purchase Volume', payment: 'Preferred Payment Method', tradingName: 'Export / Trading Company Name', authorizedRepresentative: 'Authorized Representative Name', iec: 'Import Export Code (IEC)', internationalContact: 'International Contact Number (Optional)', markets: 'Export / Distribution Markets', port: 'Primary Port / Logistics Hub', compliance: 'Required Compliance / Certification', logisticsSupport: 'Customs / Logistics Support Required?', capacityPerWeek: 'Max Products Produced Per Week (Optional - Protects Fair Working Hours)', capacityPerMonth: 'Max Products Produced Per Month (Optional)' },
  kn: { fullName: 'ಪೂರ್ಣ ಹೆಸರು', craftName: 'ಕುಶಲಕರ್ಮಿ / ಕರಕುಶಲ ಹೆಸರು', primaryCraft: 'ಮುಖ್ಯ ಕರಕುಶಲ ವರ್ಗ', specialty: 'ಕರಕುಶಲ / ಉತ್ಪನ್ನ ವಿಶೇಷತೆ', experience: 'ಕರಕುಶಲ ಅನುಭವದ ವರ್ಷಗಳು', village: 'ಗ್ರಾಮ / ಪಟ್ಟಣ', district: 'ಜಿಲ್ಲೆ', state: 'ರಾಜ್ಯ', mobile: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ', payoutMethod: 'ಆದ್ಯತೆಯ ಪಾವತಿ ವಿಧಾನ', holderName: 'ಖಾತೆದಾರರ ಹೆಸರು', accountNumber: 'ಖಾತೆ ಸಂಖ್ಯೆ', ifsc: 'ಐಎಫ್‌ಎಸ್‌ಸಿ', upi: 'ಯುಪಿಐ ಐಡಿ', societyName: 'ನೋಂದಾಯಿತ ಸಂಘದ ಹೆಸರು', registrationNumber: 'ನೋಂದಣಿ ಸಂಖ್ಯೆ', licenseDetails: 'ಸರ್ಕಾರಿ ನೋಂದಣಿ / ಪರವಾನಗಿ ವಿವರಗಳು', headOffice: 'ಮುಖ್ಯ ಕಚೇರಿ ವಿಳಾಸ', artisanCount: 'ಪ್ರತಿನಿಧಿಸುವ ಕುಶಲಕರ್ಮಿಗಳ ಸಂಖ್ಯೆ', primaryCategories: 'ಮುಖ್ಯ ಕರಕುಶಲ ವರ್ಗಗಳು', representative: 'ಸಂಘದ ಪ್ರತಿನಿಧಿಯ ಹೆಸರು', representativeMobile: 'ಪ್ರತಿನಿಧಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ', officialEmail: 'ಅಧಿಕೃತ ಇಮೇಲ್', bankAccount: 'ಕೇಂದ್ರಿಕೃತ ಬ್ಯಾಂಕ್ ಖಾತೆ', signatory: 'ಅಧಿಕೃತ ಸಹಿದಾರರ ಹೆಸರು', groupName: 'SHG / NGO ಹೆಸರು', organizationType: 'ಸಂಸ್ಥೆಯ ಪ್ರಕಾರ', manager: 'ಗುಂಪಿನ ಪ್ರತಿನಿಧಿ / ಕ್ಷೇತ್ರ ವ್ಯವಸ್ಥಾಪಕರ ಹೆಸರು', email: 'ಇಮೇಲ್', baseLocation: 'ಮೂಲ ಗ್ರಾಮ / ಸ್ಥಳ', supportedArtisans: 'ಬೆಂಬಲಿಸುವ ಕುಶಲಕರ್ಮಿಗಳ ಸಂಖ್ಯೆ', clusters: 'ನಿರ್ವಹಿಸುವ ಕ್ಲಸ್ಟರ್‌ಗಳ ಸಂಖ್ಯೆ', mainCategories: 'ಮುಖ್ಯ ಕರಕುಶಲ ವರ್ಗಗಳು', organizationId: 'ನೋಂದಣಿ / ಸಂಸ್ಥೆ ಐಡಿ', assistance: 'ಅಗತ್ಯವಿರುವ ಸಹಾಯ', deliveryAddress: 'ವಿತರಣಾ ವಿಳಾಸ', city: 'ನಗರ / ಪಟ್ಟಣ', pincode: 'ಪಿನ್‌ಕೋಡ್', preferredCategories: 'ಆದ್ಯತೆಯ ಉತ್ಪನ್ನ ವರ್ಗಗಳು', shopping: 'ಖರೀದಿ ಆದ್ಯತೆ', businessName: 'ಬುಟಿಕ್ / ವ್ಯಾಪಾರದ ಹೆಸರು', owner: 'ಮಾಲೀಕ / ಖರೀದಿ ಅಧಿಕಾರಿಯ ಹೆಸರು', gstin: 'ಜಿಎಸ್‌ಟಿಐಎನ್', businessAddress: 'ವ್ಯಾಪಾರದ ವಿಳಾಸ', businessEmail: 'ವ್ಯಾಪಾರ ಇಮೇಲ್', contact: 'ಸಂಪರ್ಕ ಸಂಖ್ಯೆ', orderVolume: 'ನಿರೀಕ್ಷಿತ ಆರ್ಡರ್ ಪ್ರಮಾಣ', preferredCrafts: 'ಆದ್ಯತೆಯ ಕರಕುಶಲ ವರ್ಗಗಳು', frequency: 'ಸಾಮಾನ್ಯ ಆರ್ಡರ್ ಅವಧಿ', resale: 'ನೀವು ಮರುಮಾರಾಟಕ್ಕಾಗಿ ಖರೀದಿಸುತ್ತೀರಾ?', companyName: 'ಸಂಸ್ಥೆ / ಕಂಪನಿ ಹೆಸರು', registeredAddress: 'ನೋಂದಾಯಿತ ಕಚೇರಿ ವಿಳಾಸ', procurementOfficer: 'ಖರೀದಿ ಅಧಿಕಾರಿಯ ಹೆಸರು', procurementEmail: 'ಅಧಿಕೃತ ಖರೀದಿ ಇಮೇಲ್', officialContact: 'ಅಧಿಕೃತ ಸಂಪರ್ಕ ಸಂಖ್ಯೆ', purpose: 'ಖರೀದಿ ಉದ್ದೇಶ', purchaseVolume: 'ನಿರೀಕ್ಷಿತ ಖರೀದಿ ಪ್ರಮಾಣ', payment: 'ಆದ್ಯತೆಯ ಪಾವತಿ ವಿಧಾನ', tradingName: 'ರಫ್ತು / ವ್ಯಾಪಾರ ಕಂಪನಿ ಹೆಸರು', authorizedRepresentative: 'ಅಧಿಕೃತ ಪ್ರತಿನಿಧಿಯ ಹೆಸರು', iec: 'ಆಮದು ರಫ್ತು ಕೋಡ್ (IEC)', internationalContact: 'ಅಂತರರಾಷ್ಟ್ರೀಯ ಸಂಪರ್ಕ ಸಂಖ್ಯೆ', markets: 'ರಫ್ತು / ವಿತರಣಾ ಮಾರುಕಟ್ಟೆಗಳು', port: 'ಮುಖ್ಯ ಬಂದರು / ಲಾಜಿಸ್ಟಿಕ್ಸ್ ಕೇಂದ್ರ', compliance: 'ಅಗತ್ಯವಿರುವ ಅನುಸರಣೆ / ಪ್ರಮಾಣೀಕರಣ', logisticsSupport: 'ಕಸ್ಟಮ್ಸ್ / ಲಾಜಿಸ್ಟಿಕ್ಸ್ ಸಹಾಯ ಬೇಕೇ?', capacityPerWeek: 'ವಾರಕ್ಕೆ ಗರಿಷ್ಠ ಉತ್ಪಾದನಾ ಸಾಮರ್ಥ್ಯ (ಐಚ್ಛಿಕ)', capacityPerMonth: 'ತಿಂಗಳಿಗೆ ಗರಿಷ್ಠ ಉತ್ಪಾದನಾ ಸಾಮರ್ಥ್ಯ (ಐಚ್ಛಿಕ)' },
  hi: { fullName: 'पूरा नाम', craftName: 'कारीगर / शिल्प का नाम', primaryCraft: 'मुख्य शिल्प श्रेणी', specialty: 'शिल्प / उत्पाद विशेषता', experience: 'शिल्प अनुभव के वर्ष', village: 'गांव / शहर', district: 'जिला', state: 'राज्य', mobile: 'मोबाइल नंबर', payoutMethod: 'पसंदीदा भुगतान तरीका', holderName: 'खाता धारक का नाम', accountNumber: 'खाता नंबर', ifsc: 'आईएफएससी', upi: 'यूपीआई आईडी', societyName: 'पंजीकृत समिति का नाम', registrationNumber: 'पंजीकरण नंबर', licenseDetails: 'सरकारी पंजीकरण / लाइसेंस विवरण', headOffice: 'मुख्य कार्यालय का पता', artisanCount: 'प्रतिनिधित्व किए गए कारीगरों की संख्या', primaryCategories: 'मुख्य शिल्प श्रेणियां', representative: 'समिति प्रतिनिधि का नाम', representativeMobile: 'प्रतिनिधि का मोबाइल नंबर', officialEmail: 'आधिकारिक ईमेल', bankAccount: 'केंद्रीय बैंक खाता', signatory: 'अधिकृत हस्ताक्षरकर्ता का नाम', groupName: 'SHG / NGO का नाम', organizationType: 'संगठन का प्रकार', manager: 'समूह प्रतिनिधि / क्षेत्र प्रबंधक का नाम', email: 'ईमेल', baseLocation: 'आधार गांव / स्थान', supportedArtisans: 'समर्थित कारीगरों की संख्या', clusters: 'प्रबंधित क्लस्टर की संख्या', mainCategories: 'मुख्य शिल्प श्रेणियां', organizationId: 'पंजीकरण / संगठन आईडी', assistance: 'आवश्यक सहायता', deliveryAddress: 'डिलीवरी का पता', city: 'शहर / कस्बा', pincode: 'पिनकोड', preferredCategories: 'पसंदीदा उत्पाद श्रेणियां', shopping: 'खरीदारी की पसंद', businessName: 'बुटीक / व्यापार का नाम', owner: 'मालिक / खरीदार का नाम', gstin: 'जीएसटीआईएन', businessAddress: 'व्यवसाय का पता', businessEmail: 'व्यावसायिक ईमेल', contact: 'संपर्क नंबर', orderVolume: 'अपेक्षित ऑर्डर मात्रा', preferredCrafts: 'पसंदीदा शिल्प श्रेणियां', frequency: 'सामान्य ऑर्डर अवधि', resale: 'क्या आप पुनर्विक्रय के लिए खरीदते हैं?', companyName: 'संगठन / कंपनी का नाम', registeredAddress: 'पंजीकृत कार्यालय का पता', procurementOfficer: 'खरीद अधिकारी का नाम', procurementEmail: 'आधिकारिक खरीद ईमेल', officialContact: 'आधिकारिक संपर्क नंबर', purpose: 'खरीद का उद्देश्य', purchaseVolume: 'अपेक्षित खरीद मात्रा', payment: 'पसंदीदा भुगतान तरीका', tradingName: 'निर्यात / व्यापार कंपनी का नाम', authorizedRepresentative: 'अधिकृत प्रतिनिधि का नाम', iec: 'आयात निर्यात कोड (IEC)', internationalContact: 'अंतरराष्ट्रीय संपर्क नंबर', markets: 'निर्यात / वितरण बाजार', port: 'मुख्य बंदरगाह / लॉजिस्टिक्स केंद्र', compliance: 'आवश्यक अनुपालन / प्रमाणन', logisticsSupport: 'क्या कस्टम्स / लॉजिस्टिक्स सहायता चाहिए?', capacityPerWeek: 'प्रति सप्ताह अधिकतम उत्पादन क्षमता (ऐच्छिक)', capacityPerMonth: 'प्रति माह अधिकतम उत्पादन क्षमता (ऐच्छिक)' },
  ta: { fullName: 'முழு பெயர்', craftName: 'கைவினைஞர் / கைவினைப் பெயர்', primaryCraft: 'முதன்மை கைவினை வகை', specialty: 'கைவினை / தயாரிப்பு சிறப்பம்சம்', experience: 'கைவினை அனுபவ ஆண்டுகள்', village: 'கிராமம் / நகரம்', district: 'மாவட்டம்', state: 'மாநிலம்', mobile: 'மொபைல் எண்', payoutMethod: 'விருப்பமான பணம் பெறும் முறை', holderName: 'கணக்கு வைத்திருப்பவரின் பெயர்', accountNumber: 'கணக்கு எண்', ifsc: 'IFSC', upi: 'UPI ஐடி', societyName: 'பதிவுசெய்யப்பட்ட சங்கத்தின் பெயர்', registrationNumber: 'பதிவு எண்', licenseDetails: 'அரசு பதிவு / உரிமம் விவரங்கள்', headOffice: 'தலைமை அலுவலக முகவரி', artisanCount: 'பிரதிநிதித்துவப்படுத்தப்படும் கைவினைஞர்களின் எண்ணிக்கை', primaryCategories: 'முதன்மை கைவினை வகைகள்', representative: 'சங்க பிரதிநிதியின் பெயர்', representativeMobile: 'பிரதிநிதியின் மொபைல் எண்', officialEmail: 'அதிகாரப்பூர்வ மின்னஞ்சல்', bankAccount: 'மைய வங்கிக் கணக்கு', signatory: 'அங்கீகரிக்கப்பட்ட கையொப்பமிடுபவரின் பெயர்', groupName: 'SHG / NGO பெயர்', organizationType: 'அமைப்பு வகை', manager: 'குழு பிரதிநிதி / கள மேலாளர் பெயர்', email: 'மின்னஞ்சல்', baseLocation: 'அடிப்படை கிராமம் / இடம்', supportedArtisans: 'ஆதரிக்கப்படும் கைவினைஞர்களின் எண்ணிக்கை', clusters: 'நிர்வகிக்கப்படும் கிளஸ்டர்களின் எண்ணிக்கை', mainCategories: 'முதன்மை கைவினை வகைகள்', organizationId: 'பதிவு / அமைப்பு ஐடி', assistance: 'தேவையான உதவி', deliveryAddress: 'டெலிவரி முகவரி', city: 'நகரம் / ஊர்', pincode: 'பின்கோடு', preferredCategories: 'விருப்பமான தயாரிப்பு வகைகள்', shopping: 'கொள்முதல் விருப்பம்', businessName: 'பூட்டிக் / வணிகப் பெயர்', owner: 'உரிமையாளர் / வாங்குபவர் பெயர்', gstin: 'GSTIN', businessAddress: 'வணிக முகவரி', businessEmail: 'வணிக மின்னஞ்சல்', contact: 'தொடர்பு எண்', orderVolume: 'எதிர்பார்க்கப்படும் ஆர்டர் அளவு', preferredCrafts: 'விருப்பமான கைவினை வகைகள்', frequency: 'வழக்கமான ஆர்டர் அதிர்வெண்', resale: 'நீங்கள் மறுவிற்பனைக்காக வாங்குகிறீர்களா?', companyName: 'நிறுவனத்தின் பெயர்', registeredAddress: 'பதிவுசெய்யப்பட்ட அலுவலக முகவரி', procurementOfficer: 'கொள்முதல் அதிகாரியின் பெயர்', procurementEmail: 'அதிகாரப்பூர்வ கொள்முதல் மின்னஞ்சல்', officialContact: 'அதிகாரப்பூர்வ தொடர்பு எண்', purpose: 'கொள்முதல் நோக்கம்', purchaseVolume: 'எதிர்பார்க்கப்படும் கொள்முதல் அளவு', payment: 'விருப்பமான பணம் செலுத்தும் முறை', tradingName: 'ஏற்றுமதி / வர்த்தக நிறுவனப் பெயர்', authorizedRepresentative: 'அங்கீகரிக்கப்பட்ட பிரதிநிதியின் பெயர்', iec: 'இறக்குமதி ஏற்றுமதி குறியீடு (IEC)', internationalContact: 'சர்வதேச தொடர்பு எண்', markets: 'ஏற்றுமதி / விநியோக சந்தைகள்', port: 'முதன்மை துறைமுகம் / லாஜிஸ்டிக்ஸ் மையம்', compliance: 'தேவையான இணக்கம் / சான்றிதழ்', logisticsSupport: 'சுங்கம் / லாஜிஸ்டிக்ஸ் உதவி தேவையா?', capacityPerWeek: 'வாரத்திற்கு அதிகபட்ச உற்பத்தி திறன் (விருப்பம்)', capacityPerMonth: 'மாதத்திற்கு அதிகபட்ச உற்பத்தி திறன் (விருப்பம்)' }
};

const getFields = (language: Language, accountType: AccountType | null): FormField[] => {
  if (!accountType) return [];
  const label = (key: FieldKey) => pickLang(fieldLabels, language)[key];
  const data = pickLang(optionSets, language);
  const text = (key: FieldKey, type: FieldType = 'text', required = true): FormField => ({ key, label: label(key), type, required });
  const select = (key: FieldKey, options: readonly string[], required = true): FormField => ({ key, label: label(key), type: 'select', options: [...options], required });
  if (accountType === 'individual_artisan') return [text('fullName'), text('craftName'), select('primaryCraft', data.crafts), text('specialty'), text('experience', 'number'), text('village'), text('district'), text('state'), text('mobile', 'tel', false), text('capacityPerWeek', 'number', false), text('capacityPerMonth', 'number', false), select('payoutMethod', data.payout), { ...text('holderName'), condition: values => values.payoutMethod === data.payout[0] }, { ...text('accountNumber'), condition: values => values.payoutMethod === data.payout[0] }, { ...text('ifsc'), condition: values => values.payoutMethod === data.payout[0] }, { ...text('upi'), condition: values => values.payoutMethod === data.payout[1] }];
  if (accountType === 'cooperative_society') return [text('societyName'), text('registrationNumber'), text('licenseDetails', 'textarea'), text('headOffice', 'textarea'), text('district'), text('state'), select('artisanCount', data.counts), select('primaryCategories', data.crafts), text('representative'), text('representativeMobile', 'tel', false), text('officialEmail', 'email'), text('capacityPerWeek', 'number', false), text('capacityPerMonth', 'number', false), text('bankAccount'), text('ifsc'), text('signatory')];
  if (accountType === 'shg_ngo') return [text('groupName'), select('organizationType', data.organization), text('manager'), text('mobile', 'tel', false), text('email', 'email'), text('baseLocation'), text('district'), text('state'), text('supportedArtisans', 'number'), text('clusters', 'number'), select('mainCategories', data.crafts), text('capacityPerWeek', 'number', false), text('capacityPerMonth', 'number', false), text('organizationId'), select('assistance', data.assistance)];
  if (accountType === 'individual_consumer') return [text('fullName'), text('mobile', 'tel', false), text('email', 'email'), text('deliveryAddress', 'textarea'), text('city'), text('state'), text('pincode'), select('preferredCategories', data.buyerCrafts), select('shopping', data.shopping)];
  if (accountType === 'boutique_retailer') return [text('businessName'), text('owner'), text('gstin'), text('businessAddress', 'textarea'), text('city'), text('state'), text('pincode'), text('businessEmail', 'email'), text('contact', 'tel', false), select('orderVolume', data.volume), select('preferredCrafts', data.crafts), select('frequency', data.frequency), select('resale', data.yesNo)];
  if (accountType === 'institutional_corporate') return [text('companyName'), select('organizationType', data.institution), text('gstin'), text('registeredAddress', 'textarea'), text('city'), text('state'), text('pincode'), text('procurementOfficer'), text('procurementEmail', 'email'), text('officialContact', 'tel', false), select('purpose', data.purpose), select('purchaseVolume', data.volume), select('payment', data.payment)];
  return [text('tradingName'), text('authorizedRepresentative'), text('gstin'), text('iec'), text('registeredAddress', 'textarea'), text('city'), text('state'), text('pincode'), text('businessEmail', 'email'), text('internationalContact', 'tel', false), select('markets', data.markets), text('port'), select('orderVolume', data.volume), select('preferredCrafts', data.crafts), select('compliance', data.certifications), select('logisticsSupport', data.yesNo)];
};

export const OnboardingFlow: React.FC<OnboardingFlowProps> = ({ language, setLanguage, onComplete }) => {
  const [step, setStep] = useState(1);
  const [userType, setUserType] = useState<UserType | null>(null);
  const [accountType, setAccountType] = useState<AccountType | null>(null);
  const [values, setValues] = useState<Record<string, string>>({});
  const [error, setError] = useState('');
  const t = { ...pickLang(copy, language), ...pickLang(languageSelectionCopy, language) };
  const data = pickLang(optionSets, language);
  const fields = useMemo(() => getFields(language, accountType), [language, accountType]);
  const update = (key: string, value: string) => { setValues(previous => ({ ...previous, [key]: value })); setError(''); };
  const chooseUserType = (next: UserType) => { setUserType(next); setAccountType(null); setError(''); };
  const validate = () => {
    if (fields.some(field => (!field.condition || field.condition(values)) && field.required && !values[field.key]?.trim())) return t.required;
    const mobile = values.mobile || values.representativeMobile || values.contact || values.officialContact || values.internationalContact;
    if (mobile && mobile.trim() && !/^(\+91[-\s]?)?[6-9]\d{9}$/.test(mobile.trim().replace(/[()]/g, ''))) return t.mobile;
    const email = values.email || values.officialEmail || values.businessEmail || values.procurementEmail;
    if (email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return t.email;
    if (values.pincode && !/^\d{6}$/.test(values.pincode)) return t.pincode;
    if (values.gstin && !/^\d{2}[A-Z0-9]{13}$/.test(values.gstin.toUpperCase())) return t.gstin;
    if (values.iec && !/^[A-Z0-9]{10}$/.test(values.iec.toUpperCase())) return t.iec;
    return '';
  };
  const complete = () => {
    const name = values.fullName || values.representative || values.manager || values.owner || values.procurementOfficer || values.authorizedRepresentative || values.societyName || values.groupName || values.businessName || values.companyName || values.tradingName || 'KalaSetu Member';
    const producer = userType === 'producer';
    const region = [values.village || values.baseLocation || values.city, values.district, values.state].filter(Boolean).join(', ');
    const capW = values.capacityPerWeek ? parseInt(values.capacityPerWeek) : undefined;
    const capM = values.capacityPerMonth ? parseInt(values.capacityPerMonth) : undefined;
    const profile = { name, role: producer ? 'weaver' : 'buyer', userType, ...(producer ? { producerType: accountType } : { buyerType: accountType }), accountType, language, capacityPerWeek: capW, capacityPerMonth: capM, email: values.email || values.officialEmail || values.businessEmail || values.procurementEmail, phone: values.mobile || values.representativeMobile || values.contact || values.officialContact || values.internationalContact, region: region || values.headOffice || values.businessAddress || values.registeredAddress || 'India', experience: values.experience || '', cooperative: values.societyName || values.groupName || '', shippingAddress: values.deliveryAddress || values.headOffice || values.businessAddress || values.registeredAddress || '', artisanId: producer ? `ART-${Math.floor(1000 + Math.random() * 9000)}` : undefined, weaverId: producer ? `WEV-${Math.floor(1000 + Math.random() * 9000)}` : undefined, buyerId: !producer ? `BYR-${Math.floor(1000 + Math.random() * 9000)}` : undefined, onboardingData: values };
    const speech = language === 'kn' ? `ಧನ್ಯವಾದಗಳು ${name}. ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಸಿದ್ಧವಾಗಿದೆ.` : language === 'hi' ? `धन्यवाद ${name}। आपका प्रोफाइल तैयार है।` : `Thank you ${name}. Your profile is ready.`;
    speakText(speech, language);
    onComplete(profile);
  };
  const next = () => { playSyntheticChime('click'); if (step === 1) return setStep(2); if (step === 2) { if (!userType || !accountType) return setError(t.required); return setStep(3); } const message = validate(); if (message) return setError(message); complete(); };
  const back = () => { playSyntheticChime('click'); setError(''); setStep(current => Math.max(1, current - 1)); };
  const renderField = (field: FormField) => { 
    if (field.condition && !field.condition(values)) return null; 
    const isNum = field.type === 'number';
    const common = { 
      value: values[field.key] || '', 
      onChange: (event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
        let val = event.target.value;
        if (isNum && val !== '') {
          const parsed = parseInt(val);
          if (isNaN(parsed) || parsed < 0) val = '0';
        }
        update(field.key, val);
      }, 
      className: 'w-full bg-cream p-3 rounded-xl border border-cream-border focus:outline-none focus:border-terracotta text-xs'
    };
    return (
      <div key={field.key} className="space-y-1">
        <label className="font-bold text-medium-beige block">{field.label}{field.required ? ' *' : ''}</label>
        {field.type === 'select' ? (
          <select {...common}><option value="">{t.select}</option>{field.options?.map(option => <option key={option} value={option}>{option}</option>)}</select>
        ) : field.type === 'textarea' ? (
          <textarea {...common} rows={3} />
        ) : (
          <input 
            {...common} 
            type={field.type || 'text'} 
            {...(isNum ? {
              min: 0,
              onWheel: (e: React.WheelEvent<HTMLInputElement>) => e.currentTarget.blur(),
              onKeyDown: (e: React.KeyboardEvent<HTMLInputElement>) => { if (e.key === '-' || e.key === 'e') e.preventDefault(); }
            } : {})}
          />
        )}
      </div>
    ); 
  };
  const accountOptions = userType === 'producer' ? (['individual_artisan', 'cooperative_society', 'shg_ngo'] as ProducerType[]) : (['individual_consumer', 'boutique_retailer', 'institutional_corporate', 'wholesale_exporter'] as BuyerType[]);
  return <div className="fixed inset-0 z-50 bg-cream flex flex-col items-center justify-center p-3 sm:p-4 overflow-y-auto"><div className="w-full max-w-4xl bg-white rounded-3xl border border-cream-border shadow-2xl overflow-hidden flex flex-col md:flex-row min-h-0 md:min-h-[600px] max-h-[95vh] md:max-h-[90vh] relative my-auto"><div className="hidden md:flex md:w-5/12 bg-indigo-custom text-cream p-8 flex-col justify-between relative overflow-hidden shrink-0"><div className="space-y-4 relative z-10"><span className="bg-mustard text-charcoal text-[10px] font-bold px-2.5 py-1 rounded-full uppercase tracking-widest">Direct Link</span><h3 className="font-serif text-2xl font-bold text-mustard leading-tight">KalaSetu Network</h3><p className="text-xs text-cream/80 leading-relaxed font-medium">{t.tagline}</p></div><div className="space-y-4 relative z-10 border-t border-cream/10 pt-6 text-xs font-semibold"><div>✓ {language === 'kn' ? 'ಧ್ವನಿ ಆಧಾರಿತ ಉತ್ಪನ್ನ ಪಟ್ಟಿ' : language === 'hi' ? 'वॉयस आधारित उत्पाद सूची' : 'Voice-to-text product listing'}</div><div>✓ {language === 'kn' ? 'ಕುಶಲಕರ್ಮಿ ಗುಣಮಟ್ಟ ಪರಿಶೀಲನೆ' : language === 'hi' ? 'कारीगर गुणवत्ता जांच' : 'Artisan quality checks'}</div><div>✓ {language === 'kn' ? 'ಸುರಕ್ಷಿತ ಎಸ್ಕ್ರೋ ಪಾವತಿ' : language === 'hi' ? 'सुरक्षित एस्क्रो भुगतान' : 'Protected escrow payments'}</div></div><p className="text-[10px] text-cream/50 font-mono tracking-widest">v1.0 CO-OP ALLIANCE</p></div><div className="flex-1 flex flex-col overflow-hidden"><div className="bg-charcoal px-6 py-3 flex items-center text-white text-[10px] uppercase font-mono tracking-wider shrink-0"><span>{t.step} {step} / 3</span><div className="flex gap-1.5 ml-3">{[1, 2, 3].map(index => <div key={index} className={`w-8 h-1 rounded-full ${step >= index ? 'bg-terracotta' : 'bg-gray-600'}`} />)}</div></div><div className="flex-1 p-6 sm:p-8 space-y-6 overflow-y-auto flex flex-col">
    {step === 1 && <div className="space-y-6 my-auto"><div className="text-center space-y-3"><div className="w-16 h-16 bg-terracotta rounded-2xl flex items-center justify-center text-white text-3xl font-serif font-bold mx-auto shadow-md">K</div><h1 className="font-serif text-3xl font-black text-terracotta tracking-tight">{t.welcome}</h1><p className="text-sm text-medium-beige font-medium px-4 leading-relaxed">{t.tagline}</p></div><div className="space-y-3.5 pt-4"><label className="text-xs font-bold text-indigo-custom uppercase tracking-wider block text-center">{t.language}</label><div className="grid grid-cols-2 gap-2.5">{SELECTABLE_LANGUAGES.map(({ code, label }) => <button key={code} onClick={() => setLanguage(code)} className={`p-3.5 rounded-2xl border-2 text-left transition flex justify-between items-center ${language === code ? 'border-terracotta bg-cream shadow-xs' : 'border-cream-border hover:border-gray-beige bg-white'}`}><span className="font-bold text-sm text-charcoal">{label}</span>{language === code && <span className="w-5 h-5 shrink-0 rounded-full bg-terracotta flex items-center justify-center text-white"><Check className="w-3 h-3" /></span>}</button>)}</div></div></div>}
    {step === 2 && <div className="space-y-5 my-auto"><div className="text-center space-y-1.5"><span className="text-[10px] text-terracotta font-extrabold uppercase tracking-widest">{t.account}</span><h2 className="font-serif text-2xl font-bold text-charcoal">{t.account}</h2></div><div className="grid gap-3 md:grid-cols-2"><button onClick={() => chooseUserType('producer')} className={`p-5 rounded-2xl border-2 text-left transition flex gap-4 items-start ${userType === 'producer' ? 'border-indigo-custom bg-cream shadow-xs' : 'border-cream-border'}`}><div className="p-3 bg-indigo-custom text-white rounded-xl"><Layers className="w-6 h-6" /></div><div><h3 className="font-bold text-sm text-charcoal">{t.producer}</h3><p className="text-xs text-medium-beige leading-relaxed mt-1">{t.producerDesc}</p></div></button><button onClick={() => chooseUserType('buyer')} className={`p-5 rounded-2xl border-2 text-left transition flex gap-4 items-start ${userType === 'buyer' ? 'border-terracotta bg-cream shadow-xs' : 'border-cream-border'}`}><div className="p-3 bg-terracotta text-white rounded-xl"><ShoppingBag className="w-6 h-6" /></div><div><h3 className="font-bold text-sm text-charcoal">{t.buyer}</h3><p className="text-xs text-medium-beige leading-relaxed mt-1">{t.buyerDesc}</p></div></button></div>{userType && <div className="space-y-2"><label className="font-bold text-medium-beige block">{userType === 'producer' ? t.producerChoice : t.buyerChoice}</label><select value={accountType || ''} onChange={event => { setAccountType(event.target.value as AccountType); setError(''); }} className="w-full bg-cream p-3 rounded-xl border border-cream-border focus:outline-none focus:border-terracotta text-xs"><option value="">{t.select}</option>{accountOptions.map(option => <option key={option} value={option}>{t.options[option]}</option>)}</select></div>}{error && <div className="bg-rose-50 border border-rose-200 text-rose-700 p-2.5 rounded-xl text-xs font-semibold flex gap-2"><Info className="w-4 h-4 shrink-0" />{error}</div>}</div>}
    {step === 3 && accountType && <div className="space-y-5"><div className="text-center space-y-1"><h2 className="font-serif text-xl font-bold text-charcoal">{t.titles[accountType]}</h2><p className="text-[11px] text-gray-beige font-medium leading-relaxed px-2">{t.detailsDesc}</p></div><div className="bg-white rounded-2xl border border-cream-border p-4 grid gap-3.5 sm:grid-cols-2 text-xs">{fields.map(renderField)}</div>{error && <div className="bg-rose-50 border border-rose-200 text-rose-700 p-2.5 rounded-xl text-xs font-semibold">{error}</div>}</div>}
    <div className="flex gap-3 pt-4 border-t border-cream-dark mt-auto"><button onClick={back} disabled={step === 1} className={`flex-1 bg-white hover:bg-cream-dark border-2 border-charcoal text-charcoal font-bold py-3.5 px-4 rounded-xl text-xs transition ${step === 1 ? 'invisible' : ''}`}>{t.back}</button><button onClick={next} className="flex-[2] bg-terracotta hover:bg-terracotta/90 text-white font-bold py-3.5 px-4 rounded-xl text-xs shadow-md flex items-center justify-center gap-1.5 transition"><span>{step === 3 ? t.create : t.continue}</span><ArrowRight className="w-4 h-4" /></button></div>
  </div></div></div></div>;
};